sudo: false

language: c

os:
  - linux
  - osx

env:
  - PATH=$HOME/.nimble/bin:$PATH

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev

before_install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
  - bash init.sh -y

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - echo PATH:${PATH}
  - set +e

script:
  - set -e
  - nim -v
  - nimble -v
  - nimble test
  - nimble docs
  - nimble build
  - set +e

before_deploy:
  - mkdir -p dist/nim_release_sample_${TRAVIS_OS_NAME}
  - cp -rf LICENSE README* bin dist/nim_release_sample_${TRAVIS_OS_NAME}/
  - tar czf dist/nim_release_sample_${TRAVIS_OS_NAME}{.tar.gz,}

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  skip_cleanup: true
  file: dist/*.tar.gz
  on:
    tags: true
