sudo: false
language: c

os:
  - linux
  - osx

env:
  - PATH=$HOME/.nimble/bin:$PATH

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev

before_install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
  - bash init.sh -y
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  # - git clone --depth 1 https://github.com/nim-lang/csources.git
  # - cd csources
  # - sh build.sh
  # - cd ..
  # - export PATH=$(pwd)/bin${PATH:+:$PATH}
  - echo PATH:${PATH}
  - set +e   # prevents breaking after_failure

script:
  - set -e
  - nim -v
  - nimble -v
  - nimble test
  - nimble docs
  - nimble build
  - nimble install
  - set +e

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  keep-history: false
  skip_cleanup: true
  file: nim_release_sample
  on:
    tags: true
